### ISSUE TITLE
Link color wont change despite CSS styling

### ISSUE THREAD

**Issue by easybeau** [syndicatefx/profile-page-hb#1]
Hi,

Thanks for this nice template!

I changed the link color in style.css like this :
a {
  color: #a329cc;
  text-decoration: none;
}

But the color is still blue in the preview website.
![Capture du 2019-05-30 10-49-21](https://user-images.githubusercontent.com/7128391/58620979-a41dd780-82c8-11e9-991c-36d68a14e16a.png)

Thanks for your help.
Isabelle

**Comment by syndicatefx** [comment]
Hi,

You are welcome.

The problem here is that i included a minified css file for those who would like to use this setup _as-is_, and only change content.

So the `profile-page-hb/public/_layout.jade` is only reading the **style.min.css**. You can change that and you will be able to view the changes you make in style.css.

Do this:

In the file `profile-page-hb/public/_layout.jade` on line 27 change

```
link(rel="stylesheet", href="/css/style.min.css")
```
to

```
link(rel="stylesheet", href="/css/style.css")
```

Hope this helps. Let me know if you need more help.
Cheers

**Comment by easybeau** [comment]
Thank you very much. It really helped!
Best regards
